name: Deploy metadata

on:
  pull_request:
    types: [closed]
    branches: [sandbox/idmQA,sandbox/idmDev,sandbox/rfppsit,sandbox/rfppdev,sandbox/rfpptest,Production]

jobs:
  DeployOnIDMQA:
    uses: sede-x/Retail-SF-Org/.github/workflows/DeployAction.yml@switchtodx
    if: (github.base_ref == 'sandbox/idmQA') && (github.event.pull_request.merged == true)
    with:
      target_branch: ${{ github.base_ref }}
      test_level_run: NoTestRun
    secrets:
      default_username: ${{ secrets.SFDX_IDMQA_USERNAME }}
      login_credentials: ${{ secrets.SFDX_IDMQA_AUTH_URL }}
  DeployOnIDMDev:
    uses: sede-x/Retail-SF-Org/.github/workflows/DeployAction.yml@switchtodx
    if: (github.base_ref == 'sandbox/idmDev') && (github.event.pull_request.merged == true)
    with:
      target_branch: ${{ github.base_ref }}
      test_level_run: NoTestRun
    secrets:
      default_username: ${{ secrets.SFDX_IDMDEV_USERNAME }}
      login_credentials: ${{ secrets.SFDX_IDMDEV_AUTH_URL }}
  DeployOnRfppDev:
    uses: sede-x/Retail-SF-Org/.github/workflows/DeployAction.yml@switchtodx
    if: (github.base_ref == 'sandbox/rfppdev') && (github.event.pull_request.merged == true)
    with:
      target_branch: ${{ github.base_ref }}
      test_level_run: NoTestRun
    secrets:
      default_username: ${{ secrets.SFDX_RFPPDEV_USERNAME }}
      login_credentials: ${{ secrets.SFDX_RFPPDEV_AUTH_URL }}
  DeployOnRfppTest:
    uses: sede-x/Retail-SF-Org/.github/workflows/DeployAction.yml@switchtodx
    if: (github.base_ref == 'sandbox/rfpptest') && (github.event.pull_request.merged == true)
    with:
      target_branch: ${{ github.base_ref }}
      test_level_run: NoTestRun
    secrets:
      default_username: ${{ secrets.SFDX_RFPPTEST_USERNAME }}
      login_credentials: ${{ secrets.SFDX_RFPPTEST_AUTH_URL }}
  DeployOnrfppsit:
    uses: sede-x/Retail-SF-Org/.github/workflows/DeployAction.yml@switchtodx
    if: (github.base_ref == 'sandbox/rfppsit') && (github.event.pull_request.merged == true)
    with:
      target_branch: ${{ github.base_ref }}
      test_level_run: NoTestRun
    secrets:
      default_username: ${{ secrets.SFDX_RFPPSIT_USERNAME }}
      login_credentials: ${{ secrets.SFDX_RFPPSIT_AUTH_URL }} 
  DeployOnProd:
    uses: sede-x/Retail-SF-Org/.github/workflows/DeployAction.yml@switchtodx
    if: (github.base_ref == 'Production') && (github.event.pull_request.merged == true)
    with:
      target_branch: ${{ github.base_ref }}
      test_level_run: NoTestRun
    secrets:
      default_username: ${{ secrets.SFDX_PROD_USERNAME }}
      login_credentials: ${{ secrets.SFDX_PROD_AUTH_URL }}
